USE [master]
GO

/****** Object:  Database [ASW]    Script Date: 02/27/2017 17:27:26 ******/
CREATE DATABASE [ASW] ON  PRIMARY 
( NAME = N'ASW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ASW.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ASW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ASW_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ASW] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ASW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ASW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ASW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ASW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ASW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ASW] SET ARITHABORT OFF 
GO

ALTER DATABASE [ASW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ASW] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ASW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ASW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ASW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ASW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ASW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ASW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ASW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ASW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ASW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ASW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ASW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ASW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ASW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ASW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ASW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ASW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ASW] SET  READ_WRITE 
GO

ALTER DATABASE [ASW] SET RECOVERY FULL 
GO

ALTER DATABASE [ASW] SET  MULTI_USER 
GO

ALTER DATABASE [ASW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ASW] SET DB_CHAINING OFF 
GO


