//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Acceptances = new HashSet<Acceptance>();
            this.DeviceLifeCycles = new HashSet<DeviceLifeCycle>();
            this.DocumentDeliveryDetails = new HashSet<DocumentDeliveryDetail>();
            this.Faulties = new HashSet<Faulty>();
            this.Faulties1 = new HashSet<Faulty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public string SerialName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DeviceName { get; set; }
        public string SerialsMatch { get; set; }
        public Nullable<int> Generation { get; set; }
    
        public virtual ICollection<Acceptance> Acceptances { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual ICollection<DeviceLifeCycle> DeviceLifeCycles { get; set; }
        public virtual ICollection<DocumentDeliveryDetail> DocumentDeliveryDetails { get; set; }
        public virtual ICollection<Faulty> Faulties { get; set; }
        public virtual ICollection<Faulty> Faulties1 { get; set; }
    }
}
