//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLifeCycle
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> DeviceStatusID { get; set; }
        public Nullable<int> TestStatusID { get; set; }
        public Nullable<int> ShippingTypeID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceStatu DeviceStatu { get; set; }
        public virtual Document Document { get; set; }
        public virtual ShippingType ShippingType { get; set; }
        public virtual TestStatu TestStatu { get; set; }
    }
}
