//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public DeviceType()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int ID { get; set; }
        public string DeviceTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
