//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faulty
    {
        public int ID { get; set; }
        public string RMANo { get; set; }
        public Nullable<int> FaultySerialNo { get; set; }
        public Nullable<int> Distributor { get; set; }
        public Nullable<int> Customer { get; set; }
        public string FaultyUnitCondition { get; set; }
        public Nullable<int> ASAction { get; set; }
        public Nullable<int> ReplacementSerialNo { get; set; }
        public Nullable<bool> HardwareRecFromCust { get; set; }
        public Nullable<System.DateTime> FaultyRecDate { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Device Device1 { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Partner Partner1 { get; set; }
        public virtual ShippingType ShippingType { get; set; }
    }
}
