//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.Documents2 = new HashSet<Document>();
            this.DocumentDeliveryDetails = new HashSet<DocumentDeliveryDetail>();
            this.Faulties = new HashSet<Faulty>();
            this.Faulties1 = new HashSet<Faulty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CRMID1 { get; set; }
        public string CRMID2 { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document> Documents1 { get; set; }
        public virtual ICollection<Document> Documents2 { get; set; }
        public virtual ICollection<DocumentDeliveryDetail> DocumentDeliveryDetails { get; set; }
        public virtual ICollection<Faulty> Faulties { get; set; }
        public virtual ICollection<Faulty> Faulties1 { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
