//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string DataString { get; set; }
        public Nullable<long> DataLong { get; set; }
        public Nullable<System.DateTime> DataDateTime { get; set; }
        public byte[] DataImage { get; set; }
        public Nullable<bool> DataBool { get; set; }
        public Nullable<decimal> DataDecimal { get; set; }
    }
}
