//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStatu
    {
        public TestStatu()
        {
            this.DeviceLifeCycles = new HashSet<DeviceLifeCycle>();
        }
    
        public int ID { get; set; }
        public string TestStatusName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TestingDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<DeviceLifeCycle> DeviceLifeCycles { get; set; }
        public virtual User User { get; set; }
    }
}
