//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASW_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Acceptances = new HashSet<Acceptance>();
            this.Documents = new HashSet<Document>();
            this.Logs = new HashSet<Log>();
            this.TestStatus = new HashSet<TestStatu>();
        }
    
        public int ID { get; set; }
        public int UserRoleID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string ReceiveEmails { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
    
        public virtual ICollection<Acceptance> Acceptances { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<TestStatu> TestStatus { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
